# The region for which all metrics passing through this server will be persisted
region: region-a

# Whether this server is running on a secure port
accessedViaHttps: false

# Topic for publishing metrics to
metricsTopic: metrics

# Topic for publishing domain events to
eventsTopic: events

kafka:
  brokerUris: 
    - monasca:9092
  zookeeperUris:
    - monasca:2181
  healthCheckTopic: healthcheck

mysql:
  driverClass: com.mysql.jdbc.Driver
  url: jdbc:mysql://monasca:3306/mon?connectTimeout=5000&autoReconnect=true
  user: monapi
  password: password
  maxWaitForConnection: 1s
  validationQuery: "/* MyService Health Check */ SELECT 1"
  minSize: 4
  maxSize: 32
  checkConnectionWhileIdle: false
  checkConnectionOnBorrow: true

databaseConfiguration:
#vertica | influxdb
  databaseType: influxdb

#Uncomment if databaseType is influxDB
influxDB:
  name: mon
  replicationFactor: 1
  url: http://monasca:8086
  user: root
  password: root

vertica:
  driverClass: com.vertica.jdbc.Driver
  url: jdbc:vertica://192.168.10.8/mon
  user: dbadmin
  password: password
  maxWaitForConnection: 1s
  validationQuery: "/* MyService Health Check */ SELECT 1"
  minSize: 4
  maxSize: 32
  checkConnectionWhileIdle: false

middleware:
  enabled: true
  #serviceIds: 100
  #endpointIds: 160
  serverVIP: devstack
  serverPort: 5000
  connTimeout: 500
  #connSSLClientAuth: true
  #keystore: etc/monasca/keystore.jks
  #keystorePass: changeit
  #truststore: etc/monasca/truststore.jks
  #truststorePass: changeit
  connPoolMaxActive: 3
  connPoolMaxIdle: 3
  connPoolEvictPeriod: 600000
  connPoolMinIdleTime: 600000
  connRetryTimes: 2
  connRetryInterval: 50
  #rolesToMatch: [user, domainuser, domainadmin]
  defaultAuthorizedRoles: [user, domainuser, domainadmin, _member_, Member]
  agentAuthorizedRoles: [monasca-agent]
  adminAuthMethod: password
  adminUser: monasca
  adminPassword: monasca
  adminToken: azertytoken
  timeToCacheToken: 600
  maxTokenCacheSize: 1048576

server:
  applicationConnectors:
    - type: http
      maxRequestHeaderSize: 16KiB  # Allow large headers used by keystone tokens


# Logging settings.
logging:

  # The default level of all loggers. Can be OFF, ERROR, WARN, INFO, DEBUG, TRACE, or ALL.
  level: INFO

  # Logger-specific levels.
  loggers:

    # Sets the level for 'com.example.app' to DEBUG.
    com.example.app: DEBUG

  appenders:
    - type: console
      threshold: ALL
      timeZone: UTC
      target: stdout
      logFormat: # TODO

    - type: file
      #currentLogFilename: ./log/monasca-api.log
      currentLogFilename: /var/log/monasca/api/monasca-api.log
      threshold: ALL
      archive: true
      #archivedLogFilenamePattern: ./log/monasca-api-%d.log
      archivedLogFilenamePattern: /var/log/monasca/api/monasca-api-%d.log
      archivedFileCount: 5
      timeZone: UTC
      logFormat: # TODO

    - type: syslog
      host: localhost
      port: 514
      facility: local0
      threshold: ALL
      logFormat: # TODO
